### ISSUE TITLE
Installation of Nest takes too much github Action time 

### ISSUE THREAD

**Issue by drodarie** [dbbs-lab/bsb-nest#8]
Every push on this repository requires the unit tests to pass, which makes sense. However, this means that Github needs to install NEST for the 3 maintained python versions. This takes a lot of dbbs allocation time for the Github action. 

Note that we noticed this issue only recently, when we pushed new features. This should not happen very often. 

While we wait for NEST to be pip installable, should we adapt the actions or install NEST differently?

**Comment by Helveg** [comment]
The NEST installation is cached though, when do you see the full installation take place? Could you link me some runs, and could you go over the commit history of a couple of commits on the main branch, to check if the NEST installation is always run entirely, or if it is sometimes indeed cached?

**Comment by drodarie** [comment]
Ah maybe I got unlucky but for my most recent commits there were no installation of NEST cached ([last](https://github.com/dbbs-lab/bsb-nest/actions/runs/9066876272/job/24910764414), [previous](https://github.com/dbbs-lab/bsb-nest/actions/runs/8928270399/job/24523459135))

**Comment by Helveg** [comment]
> Cache saved successfully

for those so the next commit should be cached, perhaps it is a side branch thing? Try to check the docs of the cache action for more info, maybe we can have it cached across branches? :s

**Comment by drodarie** [comment]
Closing issue. Github action are caching the step if and only if the whole job completed successfully. My tests were failing which is why I got multiple installation of NEST despite being on the same branch every time.
